management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:h2:mem:rentDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

